### ISSUE TITLE
Commit summary textbox height is cutoff on MacOS 15.1 with v4.9.0

### ISSUE THREAD

**Issue by joshuataylor** [git-cola/git-cola#1435] opened 2024-11-14 09:42 UTC
Since 4.9.

Happens on `Python 3.13.0` and `Python 3.12.7`.

PyQt6.

MacOS: `15.1 (24B83)`

<img width="1503" alt="image" src="https://github.com/user-attachments/assets/731e3fc4-a4ec-4b8b-b351-f9d0f8efe8ac">

Typing text "bounces" the window, but correctly shows:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/cb9cd8e7-a334-4d70-9f9c-c6cfa2c721cf">

4.8.2 works as expected.

I'm going to start figuring out which commit caused this issue, but thought I would raise it now.

**Comment by davvid** [comment] 2024-11-15 03:04
This is reproducible on Linux as well by using the Settings to choose a Diff font size that is too large for the text field.

I think the way to fix this would be to hook into where the font gets applied and set a minimum size based on the selected font. That way the field will grow if the font is larger than the default size.

I'll probably start poking around at this but if someone has a working fix I'll take that asap. Thanks for the report.

**Comment by davvid** [comment] 2024-11-15 04:37
The fix for this issue will also resolve #1301.

**Comment by davvid** [comment] 2024-11-15 04:39
Alrighty, please give this a test in your environment as well. I haven't tested this on macOS yet but the logic should be correct now and if anything would require very minor adjustment.

**Comment by davvid** [comment] 2024-11-18 04:12
I haven't been able to repro the cutoff placeholder text on Linux yet. I'll give this a test on macOS shortly.

One strange behavior on Linux (possibly macOS as well) is that when I interactively change the font the placeholder text seems to reset itself to some default font, which is kinda surprising. That *almost* seems like a Qt bug because Qt doesn't expose any way to influence the placeholder text's font besides the main `widget.setFont(...)` API on the widget itself.

Nonetheless, what I'm describing is a different, unrelated issue, and it's not really a big deal since restarting the app resolves it since the placeholder text's font will then be as expected.

Once I'm able to repro the cutoff placeholder text issue then I'll try dial in the values so that it doesn't cut off. It *seems* like its off by 1 or a few pixels at most.

The place to tweak is `def _get_preffered_height()` in `cola/widgets/spellcheck.py`. Two ideas (completely untested) would be to possibly use `2 * self.document().documentMargin()` instead of `self.document().documentMargin()` in the expression. If that's too large then adding a `+ 1` to the value there in case it's an off-by-one error might also do it.

I'd like to reproduce it locally so that I can tune it to be pixel perfect, but if you have a tweak that works in your setup that'd be useful information in case I'm not able to repro the issue.

I'll dust off my macos laptop nonetheless. What font and font size is that, in case that's related? cheers

**Comment by davvid** [comment] 2024-11-18 04:40
UPDATE ~ I fired up macOS and it reproduced right away. I'm working on a patch now.

**Closed** 2024-11-18 05:00 UTC
Labels: help wanted, usability, good first issue

**Comment by joshuataylor** [comment] 2024-11-18 05:24
Not sure if it's a scaling issue (which I thought initially it might be):

+2:

<img width="457" alt="image" src="https://github.com/user-attachments/assets/0e7fd5e2-1630-4772-be38-d66f599da7d3">

+3
<img width="250" alt="image" src="https://github.com/user-attachments/assets/4f90efdd-b45b-4c7e-b021-80faca68837a">


(I'm talking about the `_get_preferred_height`, changing the final `+ 2` to `+ 3`.)

FWIW, My scaling is `Default`, which I believe is 2x?
<img width="482" alt="image" src="https://github.com/user-attachments/assets/eee97e1d-aeb7-4aeb-a160-68b8c5e24d04">
