### ISSUE TITLE
`git-sequence-editor` invoked with wrong path on Windows

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#1385] opened 2024-03-03 10:21 UTC
My Cola is installed to `c:/Python3.12` and the sequence editor exists and can be invoked:

```console
C:\> c:\Python3.12\Scripts\git-cola.exe
C:\> git cola
```

```console
C:\> "c:/Python3.12/Scripts/git-cola-sequence-editor"
usage: git-cola-sequence-editor [-h] [--version] [-r <repo>] [--prompt] [--icon-theme <theme>]
                                [--theme <name>]
                                <filename>
git-cola-sequence-editor: error: the following arguments are required: <filename>
```

However, Cola has trouble finding the correct path when `Rebase -> Start Interative Rebase` is selected.

```console
Created autostash: d8e39161
C:\python3.12\pythonw.exe: can't open file 'C:\\bin\\git-cola-sequence-editor': [Errno 2] No such file or directory
error: There was a problem with the editor '/c/python3/pythonw.exe /C/bin/git-cola-sequence-editor'.
Applied autostash.
```

**Comment by sthalik** [comment] 2024-03-14 11:05
It doesn't work when invoked using the `git-cola.exe` wrapper:

```
C:\Python3.12\python.exe: can't open file 'C:\\Python3.12\\Scripts\\git-cola-sequence-editor': [Errno 2] No such file or directory
error: There was a problem with the editor '/C/Python3.12/python.exe /c/Python3.12/Scripts/git-cola-sequence-editor'.
```

There's also the scenario where `bin/git-cola` is copied into as `pythonw git-cola.py`, but the script doesn't reside inside the Python's installation directory in order to survive Python upgrades. It's then looking for `C:\\bin\\git-cola-sequence-editor`.

**Comment by davvid** [comment] 2024-03-17 19:32
Darn, I thought those changes would do it. I'll dust off the Windows VM and try to get to the bottom of soon.

Just so that I'm following along exactly -- can you please share the install commands that you used to install git-cola into that location? Was it a simple `pip install .` from inside a clone of the repo?

**Comment by sthalik** [comment] 2024-03-17 19:48
Yes. The procedure is:

```
> pip install .
> python bin\git-cola
```

**Comment by davvid** [comment] 2024-03-25 03:34
Thanks for sharing the exact steps you took -- that helped me narrow this down. The bug ended up being something really simple. Instead of using the `sibling_exe` variable I was assigning from the `sibling` variable.

Please give this a try again. I can at least verify that I was able to reproduce the bug with those steps and then they were fixed in my testing after making this change.

**Closed** 2024-03-25 03:33 UTC
Labels: windows, bug, packaging

**Comment by sthalik** [comment] 2024-03-25 03:38
I can confirm it works through `git-cola.exe`. However, it doesn't work when launching through `bin/git-cola`.

**Comment by davvid** [comment] 2024-03-25 07:51
Ah, that's interesting. Interestingly, I'm unable to launch `./bin/git-cola` that way because the Windows python3.11 installer doesn't seem to provide a command called `python3` so the shebang `#!` lines don't end up working out.

I can use `python ./bin/git-cola` however, and that works for both cola and the rebase editor. Do you have the same (or a different) `python3` in your $PATH?

I'm using a Git for Windows Bash shell and the Python 3.11.4 installer from python.org in a Windows 11 Pro virtual machine.

**Comment by sthalik** [comment] 2024-03-25 11:00
Here's my setup:

`%USERPROFILE%\opt` is in `Path`. Then, `bin/git-cola` copied to `~/opt/git-cola.py`. It's not invoked by `git cola` because `.py` isn't in `ComSpec`. Thus, for `git-cola.cmd` and `git-dag.cmd`, respectively:

```console
C:\Users\sthalik>type opt\git-cola.cmd
@setlocal
@set path=C:\Program Files\Git\cmd;%USERPROFILE%\opt;c:\Python3\Scripts;c:\python3;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
@start pythonw "%USERPROFILE%/opt/git-cola.py"

C:\Users\sthalik>
```

After all this needless circus is complete, I can type:

```console
~/dev/myrepo $ git cola
```

and it launches and detaches from the terminal.

This works for both `git-scm.org` Git and MSYS@ Git at the same time.

**Comment by davvid** [comment] 2024-03-26 06:39
That's super helpful. Here's some pointers in case they help.

```
pythonw "%USERPROFILE%/opt/git-cola.py"
```

The `cola/resources.py` module attempts to find things relative to the script that started the current python program (in this case, `.../opt/git-cola.py`).

That code is here: https://github.com/git-cola/git-cola/blob/e7edb2bbda9e56d4e0d1458822c49488998c6e18/cola/resources.py#L51

This suggests that if you copy `bin/git-cola-sequence-editor` to `%USERPROFILE%/opt/git-cola-sequence-editor` then it might start working because the "find sibling" behavior will find the file there and it'll be able to launch the editor from that location.

Another alternative would be to change `git-cola.cmd` so that it launches the `bin/git-cola` script using a full path into a clone of the repo rather than running a copy of it from `~/opt/`. That should make the "find sibling" behavior find the `./bin/git-cola-sequence-editor` command since the main entry point will be the script from inside the repo, which is sibling to that script.

I think what's confusing the logic right now is that the `~/opt/git-cola.py` main entry script isn't located the same directory as its companion `git-cola-sequence-editor` script.

Another detail is that we don't actually execute the command ourselves. We just set an environment variable with `/path/to/python.exe /path/to/git-cola-sequence-editor` in it and `git rebase` uses that value to execute the editor. That's why this is a little more finicky than usual -- the code has to make some assumptions about how things are installed and laid out on the file system.

Let me know if copying `git-cola-sequence-editor` into that location makes a difference.

**Comment by sthalik** [comment] 2024-03-28 09:52
> Let me know if copying git-cola-sequence-editor into that location makes a difference.

It works and it's a good workaround. Thank you.
