### ISSUE TITLE
A small window flashes rapidly while opening a repo

### ISSUE THREAD

**Issue by Poikilos** [git-cola/git-cola#1329] opened 2023-08-18 13:34 UTC
I have a screen recording of the issue: https://youtu.be/6Wxs39Up7E8

Git Cola version 4.2.1 
- Windows-10-10.0.19041-SP0 
- Python (C:\Users\Owner\AppData\Local\Programs\git-cola\Python\pythonw.exe) 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] 
- Git 2.40.1.windows.1 
- Qt 5.14.2 
- QtPy 2.0.1 
- PyQt5 5.14.2 

I looked up a solution for PyQt and found this possible solution:

```Python
mainWidget.setUpdatesEnabled(False)
# do a bunch of operations that would trigger expensive events
# like repaints
mainWidget.setUpdatesEnabled(True)
```
-from <https://stackoverflow.com/a/13781568/4541104>

I realize you use Qt but I had the same problem (tiny window flashing while adding widgets) with Tk on Windows and solved it by hiding the window while adding the widgets. So, if using the `setUpdatesEnabled` calls don't work, maybe hiding the window will work.

**Comment by mara004** [comment] 2023-08-19 11:15
I can't reproduce this on Linux. Sounds like a Windows-specific issue.

**Comment by kurtmckee** [comment] 2023-08-19 14:40
@Poikilos, this is something that has bugged me for a while. I'll try testing your suggestion and report back in the form of a PR if it works!

@mara004,

> Sounds like a Windows-specific issue

It is. I use both Windows and Linux and this is only visible to me on Windows.

**Comment by davvid** [comment] 2023-08-19 20:07
Disclaimer: I haven't used Windows as a daily driver since Windows 98.

Windows is the platform that has the most number of platform-specific hacks in the code. It's kinda interesting because Python doesn't really shield us from many of the platform-specific Windows things we end up having to do.

So.. this must be something that changed between the vista days and whatever version you're running. Can you please share your OS details so that it can help others that might see this?

Here's the part of the code that is very likely related. If a fix is possible it's probably going to be right around here:

https://github.com/git-cola/git-cola/blob/2d75d789de3b87f95a9e756d5c19bc3aa8611329/cola/core.py#L220

That section contains this relevant comment:

```
    if WIN32:
        # If git-cola is invoked on Windows using "start pythonw git-cola",
        # a console window will briefly flash on the screen each time
        # git-cola invokes git, which is very annoying.  The code below
        # prevents this by ensuring that any window will be hidden.
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags = subprocess.STARTF_USESHOWWINDOW
        startupinfo.wShowWindow = subprocess.SW_HIDE
        extra['startupinfo'] = startupinfo

        if WIN32 and not no_win32_startupinfo:
            CREATE_NO_WINDOW = 0x08000000
            extra['creationflags'] = CREATE_NO_WINDOW
```

Look at all those ugly magic numbers and subprocess tweaks -- all that is *just* for Windows.

I'm just a simple unix cat and just want to run a command; why does Windows make that so difficult? (a rhetorical question, but maybe someone knows the answer)

Note that the comment says, "The code below prevents this by ensuring that any window will be hidden."

In other words, we already fixed this behavior a long time ago for some older versions of Windows and now it stopped working, apparently.

I have no idea what magic incantation is needed to fix this but I'll happy accept a patch (especially if it cleans up those Windows hacks somehow).

I'm probably not going to spend any time on this issue and may close this issue at some point unless someone steps up to tinker around and try to fix this. If you're reading this and have a Windows Python environment then I and others would much appreciate if you could figure this out and share a solution.

I don't really have much else to offer at this point so I'll leave us with this small bit of sage advice: Life is short; use Linux.

Hopefully a kind Windows wizard can share a hacky code nugget and fix this forevermore.

**Comment by sthalik** [comment] 2023-08-22 06:43
I think this is a Qt window that's flashing and not a Git window. A Git window would pop up a console, the window that pops up is a very small one with Cola's icon.

**Comment by kurtmckee** [comment] 2023-08-23 12:50
This is indeed related to Qt, not git subprocess calls.

A total of 34 windows are opened and closed during the instantiation of the `MainView` class.

During instantiation, `MainView` calls `cola.qtutils.create_dock()` 10 times, which does the following:

* Instantiates DockTitleBarWidget, which

  * Calls `cola.qtutils.create_action_button()` twice to create "close" and "detach" buttons
  * This accounts for 2 * 10 == 20 window flashes

* Calls its `func` parameter, if passed

  * This ultimately results in additional calls to `cola.qtutils.create_action_button()`
  * This accounts for the remaining 14 window flashes

The following progression of images flash on-screen. I've grouped these by the number of separate windows that are simultaneously opened before a call is made that hides however many windows are opened.

The "close" and "detach" button windows always open in sequence and then close; other button windows will open if a lambda was passed to `create_dock()`.

![image](https://github.com/git-cola/git-cola/assets/39996/359cd02c-518c-43f8-9a21-046e7cc11751) ![image](https://github.com/git-cola/git-cola/assets/39996/eb87fcc0-facf-41c0-b0c6-762500bbafa3)

![image](https://github.com/git-cola/git-cola/assets/39996/93d49b4e-fbe6-42a9-a15c-5c3fccb4bf56) ![image](https://github.com/git-cola/git-cola/assets/39996/1f6a1a69-1274-465b-95ab-a7cfa7086981)

![image](https://github.com/git-cola/git-cola/assets/39996/ed27e976-fa00-4c00-af4d-74bce75130b9)

![image](https://github.com/git-cola/git-cola/assets/39996/62a53cfb-75a2-4db6-bf1e-a4044e1d60dd) ![image](https://github.com/git-cola/git-cola/assets/39996/7a9c0ce0-7f4f-4e2f-8452-d281048c4de8)

![image](https://github.com/git-cola/git-cola/assets/39996/f040e56b-932d-41ec-88f4-ddf41837b5c2) ![image](https://github.com/git-cola/git-cola/assets/39996/6e6496f4-c314-4d88-b33f-02e3633d45cb) ![image](https://github.com/git-cola/git-cola/assets/39996/5d91f9c8-fe5b-404d-be85-cb7114daad00) ![image](https://github.com/git-cola/git-cola/assets/39996/3ce70c4e-5307-4a6e-8cc0-0ce83ecdd295)

![image](https://github.com/git-cola/git-cola/assets/39996/47d71a7b-7dc0-4bca-9a89-8f76e009ce8f) ![image](https://github.com/git-cola/git-cola/assets/39996/818b4c2e-db62-4cba-a37f-f1fe1f32cfa9)

![image](https://github.com/git-cola/git-cola/assets/39996/38cafc73-254d-4dfe-be27-012d2ce545d1) ![image](https://github.com/git-cola/git-cola/assets/39996/86923fb0-e4c9-4d05-8d14-9e51d6b2d534) ![image](https://github.com/git-cola/git-cola/assets/39996/06982f01-ac24-458b-826b-b9517bf3dcd1) ![image](https://github.com/git-cola/git-cola/assets/39996/7f0041c1-7921-4416-b425-3dcd7252551f)

![image](https://github.com/git-cola/git-cola/assets/39996/a552174b-7bd7-449e-9bbe-0358382c0220) ![image](https://github.com/git-cola/git-cola/assets/39996/c310710e-f1ed-4ab6-98b1-df58daef6997)

![image](https://github.com/git-cola/git-cola/assets/39996/b86b1246-d880-4004-af30-821f953b5d96) ![image](https://github.com/git-cola/git-cola/assets/39996/d789217f-66e6-41a8-a039-a276c537acae)

![image](https://github.com/git-cola/git-cola/assets/39996/f52ff637-9f75-4837-bfdd-f38e55f5c500) ![image](https://github.com/git-cola/git-cola/assets/39996/f1910315-f9ea-421e-ba20-055e8a64d4f5)

![image](https://github.com/git-cola/git-cola/assets/39996/4f4487ca-8da1-419b-843d-8b875866267a) ![image](https://github.com/git-cola/git-cola/assets/39996/9a8171f2-fadc-4242-92af-e9bbb4c08833) ![image](https://github.com/git-cola/git-cola/assets/39996/0c591057-3872-4000-850b-7d0bd1343e44)

![image](https://github.com/git-cola/git-cola/assets/39996/faa4d6fb-dd22-4939-8006-2c6737102c34) ![image](https://github.com/git-cola/git-cola/assets/39996/824342ce-3567-4a1b-864c-40f095a0fc13)

![image](https://github.com/git-cola/git-cola/assets/39996/0c3ccdd8-a1f0-4714-8dbb-9866d61b9fa7) ![image](https://github.com/git-cola/git-cola/assets/39996/929958a5-d581-43b0-bcb4-c6e2850ff7d6)

![image](https://github.com/git-cola/git-cola/assets/39996/9ab80c78-694c-4cde-b88d-e9e434438dab) ![image](https://github.com/git-cola/git-cola/assets/39996/e88a760b-b293-42aa-989d-f17169224057)

![image](https://github.com/git-cola/git-cola/assets/39996/2b1874e4-8792-4be8-94c1-fb6eb04c4cbe) ![image](https://github.com/git-cola/git-cola/assets/39996/341e124b-dd3d-4168-9dee-26d6d2e8a144)

![image](https://github.com/git-cola/git-cola/assets/39996/7e7c9307-434a-4f5b-a26a-ee32cd55f5fd) ![image](https://github.com/git-cola/git-cola/assets/39996/8b4f79da-6509-4fe9-abd7-a890513cb282) ![image](https://github.com/git-cola/git-cola/assets/39996/fc5956cb-a3f2-40e0-a378-acd19458dd2c)

**Closed** 2023-08-24 07:10 UTC
Labels: help wanted, windows, good first issue
