### ISSUE TITLE
~/.config/git-cola/language file ignored on Windows

### ISSUE THREAD

**Issue by psefranek** [git-cola/git-cola#1268] opened 2022-10-23 09:56 UTC
The language config file (`~/.config/git-cola/language`) seems to be ignored on Windows OS. Application always starts with the system default locale regardless of the file content.

When I set locale manually in file `i18n.py` in method `install(locale)` like this:

```python
def install(locale):
    # pylint: disable=global-statement
    if sys.platform == 'win32':
        _check_win32_locale()
    if locale:
        _set_language(locale)
    _install_custom_language()

    # ---
    locale="en_US.UTF-8" # <--- THIS LINE IS ADDED BY ME
    # ---

    State.update(locale)
```

application starts with desired localization.

Maybe if the method `_install_custom_language()` will be changed to return the locale loaded from config file, and that return value will be assigned to the `locale` variable, everything will work as expected.

**Comment by davvid** [comment] 2022-10-25 08:22
This seems to be a duplicate of #1246 which was fixed by 437e05b1c75355c47d8b6d9ea2cf614438dac56e.

Please test the latest from git and let me know if you're still seeing this issue.

**Closed by davvid** 2022-10-25 08:22 UTC
