### ISSUE TITLE
Status widget does not automatically select a new file on some occasions

### ISSUE THREAD

**Issue by birgersp** [git-cola/git-cola#770] opened 2018-03-08 13:29 UTC
I've noticed the status widget does not automatically select a new file when I stage files. This only occurs when the file I stage is the "last in its group". For instance, if I have two unstaged files, and I select and stage the bottom of the two, no new file is selected in the status widget.
However, if I stage the first one of the two, the second file is automatically selected.

Here's a gif showing what happens when I stage the bottom file:

![before](https://user-images.githubusercontent.com/5260237/37153368-d0da21fe-22dc-11e8-9055-b7fc5074159d.gif)

I propose that the status widget could automatically select a new item from the status widget. Preferably, the next, unstaged file if any. If there's no more unstaged files in the list, perhaps the "Staged" item could be selected?

**Comment by davvid** [comment] 2022-03-25 00:57
Ahh this looks like a duplicate of #1130 #1131 and was resolved in d8dca14cd40f27b81d33af0071a71eee51bd3e23

**Closed by davvid** 2022-03-25 00:57 UTC
Labels: bug, usability
