### ISSUE TITLE
This will drop the need of providing the PUBLIC_IP ENV, as it will resolve from other sources automatically.

### ISSUE THREAD

**Issue by ab0de** [git-cola/git-cola#1296] opened 2023-02-18 05:26 UTC
This will drop the need of providing the PUBLIC_IP ENV, as it will resolve from other sources automatically.

_Originally posted by @aaronsarkissian in https://github.com/WhatsApp/proxy/pull/24_

**Comment by davvid** [comment] 2023-02-19 05:36
Thanks for the report. I don't understand this issue so I'll close this for now. Perhaps this was intended for a different repo?

**Closed by davvid** 2023-02-19 05:36 UTC
