### ISSUE TITLE
CTRL +  Backspace shortcut breaks standard typing functionality

### ISSUE THREAD

**Issue by penguinpowernz** [git-cola/git-cola#504] opened 2015-09-30 04:31 UTC
Love this tool, but a minor niggle with the new release is that I can no longer do CTRL+Backspace to delete a whole word.  Is it possible to make the shortcuts modifiable, or change the shortcut so it doesn't conflict with standard typing functionality?  Otherwise I will just have to learn to CTRL+Left, CTRL+DELETE.

**Comment by davvid** [comment] 2015-09-30 06:16
I believe this is a duplicate of #453, which was fixed in the previous release (your distro probably hasn't picked up v2.3 yet, it seems.. are you on v2.2 or earlier?).  Can you try the latest from master?

I just tried this and it seems to work fine here.  I'm on debian sid. I'll be releasing v2.4 soon, but this should have already been fixed in v2.3.

**Closed by davvid** 2015-09-30 06:16 UTC

**Comment by davvid** [comment] 2015-09-30 06:18
Also, make sure that the commit message editor has focus (press Ctrl+1, or click in there) otherwise the status widget might have focus, and handle the hotkey.

**Comment by penguinpowernz** [comment] 2015-09-30 21:34
You are correct, sir!  I am running v2.2.1, so I'll just wait eagerly for downstream to package it (your second comment doesn't work for me but thats OK).

Thanks! :+1:
