### ISSUE TITLE
Slow operations on Windows (due to slow git processes)

### ISSUE THREAD

**Issue by nyanpasu64** [git-cola/git-cola#1153] opened 2021-08-17 11:07 UTC
Basically as far as I can tell, Git Cola has been slow to perform basically all operations on Windows: starting up (multiple seconds), staging and unstaging files, committing, switching between regular and amend mode (each has around half a second of UI unresponsiveness).

In SnakeViz, I found that a lot of the slowdown occurs when waiting for `subprocess.Popen.communicate` calls.

In procmon's tree view (opened through Ctrl+T in procmon), I found that opening/picking a repository calls dozens of Git processes (causing a long delay after the window opens but before the UI becomes responsive), each one launching a conhost (omitted from the trace, sorry) and a second git process, and the `git -c diff.suppressBlankEmpty=false -c log.showSignature=false submodule status` launching a shell and creating many child Git processes, taking a lot longer than the other git commands.

Pressing Ctrl+M to switch into amend view launches 8 git processes, each with a Conhost.exe and git.exe.

I've attached a Procmon trace ("cola.PML") of launching git-cola with no repo (fast-ish), opening a repo (very slow), and pressing Ctrl+M (somewhat slow).

GitExtensions (a Windows-specific Git GUI) is considerably faster to switch between repositories, or open or reload the Commit dialog. "gitext refresh commit dialog.PML" contains a trace of me reloading the Commit dialog in GitExtensions . It only launches 5 Git processes, and the first 3 run concurrently reducing the time spent waiting for them to exit.

"gitext switch repo.PML" contains a trace of me switching repositories. It also runs many Git commands, but nowhere near as many as git-cola, and many run concurrently.

The duration each git process takes to complete seems largely similar between the runs, though it is unfortunate how each git process (installed using Git for Windows) takes a lot longer to finish than its child conhost or git process doing the real work (I think Git uses slow shim processes if you tell git to only put git.exe and not Git Bash in PATH).

Traces: [procmon.zip](https://github.com/git-cola/git-cola/files/6999297/procmon.zip)

**Comment by birgersp** [comment] 2021-12-01 08:03
Git Cola is very slow for me, aswell. When I switch to the window and refresh (f5) to commit my changes I usually have to wait 3-5 seconds for it to finish the refresh. If I compare to e.g. git-gui it is instant. I personally think this is a big issue with git-cola.
I have not investigated the issue like @nyanpasu64 have, so I cannot really say _why_ it is slow.

**Comment by davvid** [comment] 2021-12-19 23:42
Interesting that git-gui would be faster. You can see what's getting run by running:

    export GIT_COLA_TRACE=1

and then launching cola from that environment. That can help debug which git operations are slow.

We do have a knob you can configure to make cola ignore untracked files. This can speed things pu.

    git config gui.displayuntracked false


Please let me know if any of these point to an operation that is particularly slow.

BTW this is one of those use cases (spawning external processes) where Linux is much faster than Windows.

The submodule status is an interesting note. I don't think we've looked at having ways to avoid that query. If that's indeed a slow code path there may be things we can do to amortize that.

**Comment by birgersp** [comment] 2021-12-20 07:33
Here is a trace output of me doing 3 things:

1. Open a repository
2. Selecting a file in the Status widget
3. Hitting refresh (f5)

`git -c diff.suppressBlankEmpty=false -c log.showSignature=false version
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file C:\Users\myuser\.gitconfig --list --includes
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file C:\Users\myuser\repo\tools\.git\config --list --includes
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config -z --get-all --show-origin cola.icontheme
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file C:\Users\myuser\.gitconfig --list --includes
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file C:\Users\myuser\repo\tools\.git\config --list --includes
git -c diff.suppressBlankEmpty=false -c log.showSignature=false version
git -c diff.suppressBlankEmpty=false -c log.showSignature=false update-index --refresh
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-index --cached -z HEAD --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-files -z --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --others --exclude-standard --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false rev-parse --symbolic-full-name HEAD
git -c diff.suppressBlankEmpty=false -c log.showSignature=false merge-base HEAD origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-tree --name-only --no-commit-id -r -z c1dcd667f74121a9c121b2da395611a5abf567ee origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false remote
git -c diff.suppressBlankEmpty=false -c log.showSignature=false for-each-ref --format=%(refname) --sort=version:refname
git -c diff.suppressBlankEmpty=false -c log.showSignature=false submodule status
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff --unified=3 --no-ext-diff --no-color -M --stat HEAD
git -c diff.suppressBlankEmpty=false -c log.showSignature=false update-index --refresh
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-index --cached -z HEAD --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-files -z --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --others --exclude-standard --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false merge-base HEAD origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-tree --name-only --no-commit-id -r -z c1dcd667f74121a9c121b2da395611a5abf567ee origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false remote
git -c diff.suppressBlankEmpty=false -c log.showSignature=false for-each-ref --format=%(refname) --sort=version:refname
git -c diff.suppressBlankEmpty=false -c log.showSignature=false submodule status
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff --unified=3 --no-ext-diff --no-color -M --stat HEAD
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff -M --patience --submodule --no-color --no-ext-diff --unified=3 -- vscode/keybindings.json
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff -M --patience --submodule --no-color --no-ext-diff --unified=3 -- vscode/keybindings.json
git -c diff.suppressBlankEmpty=false -c log.showSignature=false add --force --verbose -- windows/Microsoft.PowerShell_profile.ps1 vscode/settings.json vscode/keybindings.json
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-index --cached -z HEAD --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-files -z --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --others --exclude-standard --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false merge-base HEAD origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-tree --name-only --no-commit-id -r -z c1dcd667f74121a9c121b2da395611a5abf567ee origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false rev-parse --quiet --verify HEAD
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff -M --cached --patience --submodule --no-color --no-ext-diff --unified=3 HEAD -- windows/Microsoft.PowerShell_profile.ps1
git -c diff.suppressBlankEmpty=false -c log.showSignature=false update-index --refresh
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-index --cached -z HEAD --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-files -z --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --others --exclude-standard --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false merge-base HEAD origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-tree --name-only --no-commit-id -r -z c1dcd667f74121a9c121b2da395611a5abf567ee origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false remote
git -c diff.suppressBlankEmpty=false -c log.showSignature=false for-each-ref --format=%(refname) --sort=version:refname
git -c diff.suppressBlankEmpty=false -c log.showSignature=false submodule status
git -c diff.suppressBlankEmpty=false -c log.showSignature=false rev-parse --quiet --verify HEAD
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff -M --cached --patience --submodule --no-color --no-ext-diff --unified=3 HEAD -- windows/Microsoft.PowerShell_profile.ps1`

I noticed that there is a "halt" between these two trace lines:

`git -c diff.suppressBlankEmpty=false -c log.showSignature=false for-each-ref --format=%(refname) --sort=version:refname
# (no output for about 2 seconds)
git -c diff.suppressBlankEmpty=false -c log.showSignature=false submodule status`

I notice the same two commands are run if I do a stage file (ctrl+s).

So either of those two lines are probably what's causing the "pause".

> BTW this is one of those use cases (spawning external processes) where Linux is much faster than Windows.

(Yeah I'd be switching to Linux in a heartbeat, if my workplace would let me)

**Comment by birgersp** [comment] 2021-12-20 07:53
I tried a large repo now. Several of the commands (looking at the trace) are slow.

It would be easier to highlight the slow operations if the trace could output some timestamp, perhaps that is something that can be added (another env var?)

**Comment by birgersp** [comment] 2022-02-03 09:29
Sorry for being that guy but this HAS to be fixed. [Half of all developers are on Windows](https://insights.stackoverflow.com/survey/2021#section-most-popular-technologies-operating-system), git-cola isn't usable for me in this state.

**Comment by davvid** [comment] 2022-02-05 11:43
Can you confirm that running `git submodule status` from the shell also takes a couple of seconds?

If the hang is before that line gets printed then likely the time is being spent there.

Sometimes git repos require periodic `git fetch --prune && git gc --aggressive` maintenance to make git's queries fast again. This program is written in the UNIX style where we fork lots of small processes and we expect those things to be fast.

A nice goal would be to not run all of the blocking operations on the main thread, which could help a bit, but that's a big rework. I bet there are some low hanging fruit here that can make a big difference.

A bigger impact is we can do things like make it so that none of the submodules queries happen when the submodules widget isn't being displayed. Do you use that widget a lot?

Let me know if that is indeed the slowest operation. I'm going to look at lazy loading that information in the meantime under the assumption that it'll help.

**Comment by davvid** [comment] 2022-02-05 11:55
good idea on the making the trace more helpful. I'll push up a change shortly that adds elapsed time indicators to the log messages. That'll make it really easy to tell which command is the slow one.

**Comment by birgersp** [comment] 2022-02-05 11:56
I would say `git submodule status` takes about 1 second, while a git-cola refresh (I hit F5) takes about 3. That's probably not very helpful but I'm not sure how to "time" the commands.

**Comment by davvid** [comment] 2022-02-05 12:03
I just pushed up a change that adds times to the trace output to help get better data. If we can shave 1 second off that 3 then that's already a 33% improvement. Thanks for confirming that `git submodule status` is a particularly heavy operation.

I'll take a stab at the submodule lazy loading later today after I get a chance to merge #1200. Thanks for your help digging into the root causes. There's more we can do.

**Comment by davvid** [comment] 2022-02-05 21:24
This issue is a duplicate of #499. We have a number of other related issues linked there with further perf ideas.

Once we hear back as to whether 7ce11e3f4b93a94e99afd1db0cd3fdc5a6f7a8e1 is helping I'll probably close this issue and continue pushing on it over there.

**Comment by birgersp** [comment] 2022-03-03 20:50
@davvid thanks a lot for your dedication and work on this

I've been away for a while but finally I managed to give it a spin. This is the trace for opening a repo:

```
# 0.061s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file C:\Users\birge\.gitconfig --list --includes
# 0.055s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file C:\Users\birge\repo\kaboom\.git\config --list --includes
# 0.057s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-index --cached -z HEAD --
# 0.066s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-files -z --
# 0.059s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --others --exclude-standard --
# 0.057s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false merge-base HEAD origin/master
# 0.057s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-tree --name-only --no-commit-id -r -z 0265831cc59d0b223cc3876b272f9b4d6514c18f origin/master
# 0.055s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false remote
# 0.058s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false for-each-ref --format=%(refname) --sort=version:refname
# 0.960s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false submodule status
# 0.060s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff -M --patience --submodule --no-color --no-ext-diff --unified=3 -- server/src/db/ServerDB.ts
```

As you can see the submodule status takes about 1 second.

I haven't fully grasped what you changed but I can say right away that it seems to perform great now! I (and I am sure other Windows people aswell) truly do appreciate that

**Comment by davvid** [comment] 2022-09-28 02:03
I just eliminated another 4 calls to `git` during the startup sequence so it should startup a little faster now too.

Thanks for your feedback thus far! I'll close this issue now but we'll keep pushing on it in the context of #499. Thanks again!

**Closed by davvid** 2022-09-28 02:03 UTC
Labels: help wanted, windows, perf
