### ISSUE TITLE
Version 4.2.0 and 4.1.0 do not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by NielBuys** [git-cola/git-cola#1286] opened 2023-02-06 07:43 UTC
Version 4.2.0 and 4.1.0 do not work on Ubuntu 20.04. See screenshot of messages looks like I need new pyqt packages. Can you assist in what I need to load to get the latest git-cola up and running. I had to hard reset to version 4.0.4 to get my git-cola up and running.

![image](https://user-images.githubusercontent.com/8427483/216912731-8143e241-9084-44b7-861b-7318f673be6c.png)

I am running my git-cola from branch. So I did a git pull to load the newest version.

Thanks in advance

**Comment by davvid** [comment] 2023-02-07 05:53
This is unexpected. We should still be compatible with those versions.

Hmm... here's a wild guess. Does it work correctly if you move the `qtpy` directory aside (eg. rename it to `qtpy.tmp`? [0]

Does it work better if you use `python3 ./bin/git-cola` to run it from the source tree? [1]

Does this command work?  `python3 -c 'import PyQt5.QtWidgets'`?


I ask [1] because running `git-cola` may be running an older version from `/usr/bin` unless you've setup your environment to make the source tree's `./bin` directory available in your $PATH.

We did somewhat recently upgrade our vendored `qtpy`, but in theory it should still be compatible. That's why I suggested trying [0] since it should then prefer the distro-provided qtpy package.

I should probably install ubuntu 20 in a VM for testing as well. Let me know if any of these help.

**Comment by NielBuys** [comment] 2023-02-07 07:18
1. Ok renaming the qtpy folder to qtpy.tmp worked git-cola started. (I renamed it back before I did the next tests)
2. Running "python3 ./bin/git-cola" did not work. It still gave the message.
3. Command "python3 -c 'import PyQt5.QtWidgets'" didn't show anything.

![image](https://user-images.githubusercontent.com/8427483/217173735-2822651b-3f6a-4848-a2c1-84f54331a0fd.png)

Ok must I rename the qtpy folder for now or do you want me to the revert back to 4.0.4?

Thanks for reply

**Comment by NielBuys** [comment] 2023-02-07 07:24
Just thought of it. The second command I should probably have run it in the git-cola folder. It still did not work.
 
![image](https://user-images.githubusercontent.com/8427483/217176520-9ad0b8e2-46ac-4ff0-8c46-b27c72bfa455.png)

**Comment by davvid** [comment] 2023-02-08 04:08
Thanks for the debugging output. Since (1) works for now that should get you going for trying the latest version.

I installed ubuntu20 in a VM and I'm able to reproduce the error. I do it by running:

```bash
python3 -c 'import qtpy'
```

and the error it reports is:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/basil/git-cola/qtpy/__init__.py", line 57, in <module>
    from packaging.version import parse
ModuleNotFoundError: No module named 'packaging'

```

Let me know if you see the same thing when you run that command. If so that means the tweaks i'm about to make are going to do the right thing.

That would explain it -- qtpy has more dependencies these days so moving it aside lets it use your distro-provided version.

I like to keep the dependencies minimal for the in-tree files so I'm going to rip that dependency out from the vendored copy I keep in-tree. I don't mind qtpy having that dependency when installed in a virtualenv, but the source tree has a stricter policy of not having any external dependencies.

Thanks for the heads-up. Once this issue closes you should be able to move `qtpy.tmp` back to `qtpy` and then pull to pickup the fix.

**Closed** 2023-02-08 04:26 UTC

**Comment by davvid** [comment] 2023-02-08 04:42
This is fixed now. I was able to run from the source tree inside an ubuntu 20 VM using the latest version in Git. Let me know if you run into anything else.

**Comment by NielBuys** [comment] 2023-02-08 07:01
Thanks for the help. It works now
