### ISSUE TITLE
dag flashes again when building in ignored subdirectory

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#620] opened 2016-11-03 11:06 UTC
It didn't happen before merging @living180's branch. Shortly after it did and I fail to find the breaking commit. Try merely adding ignored files and see how dag refreshes.

**Comment by davvid** [comment] 2016-11-05 21:17
Hmm are you running on Windows or Linux?  The filesystem monitoring implementation is unique to each one. I don't observe this behavior on Linux so I'm going to assume that this problem only exists in the Windows filesystem notifier.  Please let me know if this is not the case.

I did manage to get a slightly newer Windows environment setup so I'll try to take a look next week (unless someone beats me to it).  If this fix is nice and simple then I'd like to include it as the last topic that gets merged in before the upcoming v2.9 release.

**Comment by sthalik** [comment] 2016-11-06 11:36
This is Windows.

**Comment by living180** [comment] 2016-11-15 12:59
@sthalik -I just did some basic testing of this and am not able to reproduce it on Windows.  I tried both git-cola and git-dag against a git checkout of git-cola itself.  Touching a file tracked by git (e.g. a .py file) caused a refresh, but touching an ignored file (e.g. a .pyc file) did not.  Creating a file an an ignored directory (e.g. in test/tmp) also did not cause a refresh.

I'm happy to look into this some more, but I'll need more information on how to reproduce what you are seeing.

**Comment by sthalik** [comment] 2017-05-06 08:28
@living180 it persists when building. It doesn't matter if I ignore `/build*/` or put `*` in build directory's `.gitignore`. All the build directory files are untracked. How can I help you reproduce this case?

**Comment by sthalik** [comment] 2017-05-06 08:29
FWIW the project builds with MS Visual C++ 2015 and newer and can be built using precompiled official Qt 5.

I forgot all this time -- the partition the project is on is ReFS, not NTFS. I keep all heavy storage out of NTFS.

**Comment by living180** [comment] 2017-05-17 14:12
@sthalik sorry for the delay in getting back with you.  At this point, I might have to create a branch with some extra instrumentation for you to run to help determine what is going on.  If that is acceptable, can you tell me what version of git-cola you normally run (e.g. git master, v2.11, etc.) and I'll create a new branch based on that.

**Comment by sthalik** [comment] 2017-05-17 15:08
@living180 I'm using master. Thanks.

**Closed** 2017-09-05 02:22 UTC
Labels: usability, win32

**Comment by sthalik** [comment] 2017-09-05 02:51
Works. Thanks!
