### ISSUE TITLE
(upstream bug) incompatibility with PyQt5 5.15.1

### ISSUE THREAD

**Issue by zougloub** [git-cola/git-cola#1103] opened 2020-11-30 16:36 UTC
Gives:
```
cola/observable.py", line 15, in add_observer
    observers.add(observer)
TypeError: unhashable type: 'PyQt5.QtCore.pyqtBoundSignal'
```

Should be fixed in PyQt5 5.15.2.

Same as https://github.com/pytest-dev/pytest-qt/issues/316

**Comment by living180** [comment] 2020-11-30 17:07
Duplicate of #1101.

**Closed by living180** 2020-11-30 17:07 UTC
