### ISSUE TITLE
DAG hangs at diff.py(993): update_text: QtWidgets.QLabel.resizeEvent(self, event) in certain environment

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#861] opened 2018-07-26 10:34 UTC
This bug only reproduced on my laptop~~, only in snapped version~~, not 100%, for some reason.

The very last calls:

```python
diff.py(989):             self.update_text(event.size().width())
 --- modulename: diff, funcname: update_text
diff.py(974):         self._display = self._text
diff.py(975):         if not self._elide:
diff.py(977):         text = self._metrics.elidedText(self._template,
diff.py(978):                                         Qt.ElideRight, width-2)
diff.py(979):         if text != self._template:
diff.py(990):             block = self.blockSignals(True)
diff.py(991):             self.setText(self._display)
diff.py(992):             self.blockSignals(block)
diff.py(993):         QtWidgets.QLabel.resizeEvent(self, event)
 --- modulename: diff, funcname: resizeEvent
diff.py(988):         if self._elide:
diff.py(989):             self.update_text(event.size().width())
 --- modulename: diff, funcname: update_text
diff.py(974):         self._display = self._text
diff.py(975):         if not self._elide:
diff.py(977):         text = self._metrics.elidedText(self._template,
diff.py(978):                                         Qt.ElideRight, width-2)
diff.py(979):         if text != self._template:
diff.py(990):             block = self.blockSignals(True)
diff.py(991):             self.setText(self._display)
diff.py(992):             self.blockSignals(block)
diff.py(993):         QtWidgets.QLabel.resizeEvent(self, event)
```

Full python trace (14.3MiB): [traces.log](https://github.com/git-cola/git-cola/files/2231534/traces.log)

**Comment by Lin-Buo-Ren** [comment] 2018-07-26 10:42
The issue vanished after I login an XFCE session, then switched back to KDE Plasma...

**Comment by Lin-Buo-Ren** [comment] 2018-07-31 06:44
Closing as it doesn't seem to be a Git Cola bug (and it works now for some reason).

**Comment by brlin-tw** [comment] 2022-01-04 06:57
Hello, long time no see.

I am again can reproduce the similar issue on KDE Plasma 5.22.5(Ubuntu 21.10), this time I found a possible workaround:

1. Quit Git Cola
2. Edit ~/.config/git-cola/settings
3. Remove the gui_state > gitdag > geometry property
4. Reopen Git Cola

Not sure if this is fixable though, but as a workaround we can probably drop the property and retry when detecting a hang.

**Comment by davvid** [comment] 2022-01-25 04:45
Interesting. The window geometry stuff is code that basically does https://doc.qt.io/qt-5/restoring-geometry.html for restoring the window state. That corner of Qt seems to be prone to issues between Qt and the window manager.

I don't know if there's any way to detect a hang. Do you see any messages in the terminal if you launch cola from a shell?

There are other approaches (like trying to save/restore the positions/sizes ourselves) but that has other issues like not properly handling the fullscreen / maximized state on windows / macos; so far the restoreGeometry() approach has been the most robust.

what's the distro? are you using qt5ct?

**Comment by brlin-tw** [comment] 2022-01-25 07:15
> I don't know if there's any way to detect a hang. Do you see any messages in the terminal if you launch cola from a shell?

Not much in particular with the default logging verbosity.

> what's the distro?

Ubuntu 21.10 (with KDE desktop environment)

> are you using qt5ct?

It's not installed in my system so I guess no...?

**Comment by davvid** [comment] 2022-02-05 21:04
This seems to be a duplicate of https://github.com/git-cola/git-cola/issues/760.

There's an answer in that issue. I'm going to close this issue, and I'll be taking the notes from #760 and adding them to the docs.

**Closed by davvid** 2022-02-05 21:04 UTC
