### ISSUE TITLE
Feature request: auto-fetch in background and notify

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#952] opened 2019-04-23 09:48 UTC
There is a great functionality in one of competitor application - you may enable automatic fetch for each customizable period of time (eg. 1 minute) and - if there is change on remote - it notifies user.

If maintainers doesn't have enough resources - would pull-request with such feature be welcome?

**Comment by piegamesde** [comment] 2019-04-25 07:40
Duplicate of #361

**Comment by davvid** [comment] 2024-09-07 06:48
https://github.com/git-cola/git-cola/commit/3cb3c91654e4d71af154f2b0dd21936e3535296e

**Closed** 2024-09-07 06:48 UTC
