### ISSUE TITLE
Local commentChar config is not honored.

### ISSUE THREAD

**Issue by rnovacek** [git-cola/git-cola#766] opened 2018-02-28 10:24 UTC
I'm working on a project that has a convention that all commit messages start with a hash sign `#` and id of a github issue.

For example:
```
#15 Fix bug in whatever feature
```

Unfortunately Git Cola doesn't allow me to enter the hash sign as first character of the commit message. I have to use terminal to do that commit (`git commit -m '#15 Fix bug in whatever feature` or `git commit` and enter the message in editor - with changed `commentchar` config to something else).

Given that git commits starting with `#` sign are legal, it would be nice if Git Cola could allow creating them.

**Comment by Vdragon** [comment] 2018-02-28 13:47
Probably a duplicate of #383

**Comment by rnovacek** [comment] 2018-02-28 14:11
Ah, I just realized that Git Cola takes global `core.commentChar` in account when checking the commit message. After running `git config --global core.commentChar ";"` I can use `#` in commit message.

But it would be great if it would also honor local commentChar settings.

**Comment by davvid** [comment] 2018-03-01 07:54
Nice catch.  It wasn't handling the case when the repository changes, which also has a side-effect of not honoring the local commentchar if it was already set globally.  I'll be pushing a fix for this shortly, give it a try.  Thanks for the report.

**Closed** 2018-03-01 08:06 UTC

**Comment by rnovacek** [comment] 2018-03-01 08:13
Works great now, thanks!
