### ISSUE TITLE
feature request: spell check in commit message box

### ISSUE THREAD

**Issue by boxerab** [git-cola/git-cola#1218] opened 2022-03-20 13:03 UTC
First of all, thank you all for this excellent software !

For this feature, not sure how much work it would entail, but it sure would be nice to have some spell checking before making a commit.

**Comment by davvid** [comment] 2022-12-24 03:49
Duplicate of #1070

Meta: there's currently no simple way to add spellchecking to QLineEdit, which is why this has sat dormant.

**Closed by davvid** 2022-12-24 03:49 UTC
