### ISSUE TITLE
Homebrew install on MacOS X does not install git-cola.app

### ISSUE THREAD

**Issue by draper-lucid** [git-cola/git-cola#1322] opened 2023-07-24 20:03 UTC
I really would rather not have my guys pull the source code and run make in order to have the app icon. Could it be added as part of the homebrew install?

**Comment by kurtmckee** [comment] 2023-08-25 11:58
I think this is not a bug in git-cola, but rather [an issue in homebrew's "formula" for git-cola](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/g/git-cola.rb), which is not managed by this project.

I recommend reaching out to the homebrew project to resolve this.

@davvid I think this issue can be closed.

**Comment by davvid** [comment] 2023-10-21 20:10
Homebrew/homebrew-core#152016 should resolve this issue.

**Comment by davvid** [comment] 2023-10-22 23:57
@draper-lucid I tried my best in the linked issue to add the `make git-cola.app` artifact to the homebrew installation but it may not get merged upstream.

The homebrew maintainers are giving some push back to the idea (please see the linked issue) so unfortunately I might have to close this issue in an unresolved state if they don't accept the contribution. I'm :crossed_fingers: that they might reconsider, but I'm not holding my breathe either. :beers:

**Closed** 2023-10-23 15:39 UTC
