### ISSUE TITLE
Large icons and no auto focus on OS X

### ISSUE THREAD

**Issue by sitnikovme** [git-cola/git-cola#572] opened 2016-05-08 11:19 UTC
git-cola: version starting from version 2.4 and upto current (2.6)
OS X: 10.11.4 (15E65)
MacBook Pro (Retina, 15-inch, Mid 2015)

1) I see very large icons comparing with v2.3

v2.6
![git-cola icons](https://cloud.githubusercontent.com/assets/5707198/15097508/70121d9e-152e-11e6-8d85-bb9425556669.png)

v2.3
![git-cola icons 2 3](https://cloud.githubusercontent.com/assets/5707198/15097530/160c9fc6-152f-11e6-8dc9-fcef4a5e8694.png)

2) Focus is not auto set to currently selected file when I switch between files (using up and down arrow keys) in "Status" sub-window and when selection go out window boundaries. So, when I use keyboard to switch between files, the content of the "Status" window stays static.

**Comment by davvid** [comment] 2016-05-09 02:27
I'm closing this since it's a duplicate of #550 

I wonder if this is a PyQt4 issue that's already been fixed in PyQt5 or PySide. At the code level the only difference we made was swapping in a resolution-independent .svg file in place of a fixed-size .png.

If this is a PyQt4 issue then #232 is related so we'll need to make a choice between PyQt5 and PySide.

I'll test this again next time I have a chance. It's odd because when I tried it last time on my 15" retina MBP I didn't see this issue. I don't remember if it was running yosemite or elcap or whatever as it's been a long time since I've used it. FWIW I don't see this issue on my retina (quad-hd) linux laptop so the issue seems to be something related to PyQt4.

Regarding 2) I can't reproduce that one either, and may similarly not be an issue when we upgrade to Qt5. I can imagine that maybe Apple changed some APIs between mavericks and el cap that broke Qt4 so the only way to support bleeding edge osx versions would be to use Qt5.

**Closed by davvid** 2016-05-09 02:27 UTC
