### ISSUE TITLE
RuntimeError: the sip module implements API v12.0 to v12.8 but the PyQt5.QtCore module requires API v12.9

### ISSUE THREAD

**Issue by Scaum** [git-cola/git-cola#1215] opened 2022-03-11 10:35 UTC
Title says it all.

Running Kali (so Debian based). Installation with apt or pip both result in the same runtime error. is there a fix for this ?

**Comment by davvid** [comment] 2022-03-11 17:57
There's a few things you can check. Here's some questions that'll help narrow down on it.

* Did you run `pip` as root? Hopefully you didn't; if so it may have installed stuff into the system-wide python locations. That is a bit harder to fix and may require you to use `apt` to reinstall the system python, pip, sip and pyqt5 pacakges.
* Did you run `pip` as a non-root normal user (your user account)? If so, there may be cruft that it left in `~/.local/lib/python*` that removing may help.

Here's my rule of thumb. It's almost never a good idea to run `pip` as root or outside of a virtualenv because it's going to install stuff in these "global" locations, leading to these kinda problems.

Here's something you can try:

```
python3 -m venv env3
```

Now you have a virtualenv called `env3` that contains all of the dependencies. You can then use the usual python virtualenv workflows to install cola:

```
source env3/bin/activate
pip install --editable .

# This enables the "SendToTrash" feature (optional)
make requirements-optional

# If you plan to build the documentation (optional)
make requirements-dev

git cola
```

Or if you're like me and you prefer to use [vx](https://github.com/davvid/vx) then you can do without having to source the `activate` script so that you don't have to worry about your shell environment being setup correctly (I'm not a fan of `source env3/bin/activate`). These are equivalent to the steps above

```
vx env3 pip install --editable .
vx env3 make requirements-optional
vx env3 make requirements-dev
vx env3 git cola
```

Since it's a virtualenv this totally works too if you want to eschew both `vx` and virtualenv activation...

```
./env3/bin/python ./bin/git-cola
```

Hope that helps! That'll get things running because it's going to use the virtualenv. Your system is technically in a broken state, so that might be worth digging into.

Here is a simple test case you can use to see the root cause (outside of any virtualenv with just your stock system):

```
python3 -c 'import PyQt5.QtCore'
```

That command above should trigger the `RuntimeError` in the title.

**Comment by davvid** [comment] 2022-03-11 18:00
BTW we already have an alpha `pip install git-cola` available on pypi:

https://pypi.org/project/git-cola/

It's "alpha" because I've been tearing about the python build system lately so that it's actually pip-installable. You showed up at just the right time ~ it used to be a bit harder to install but now that we support `pip` it's hopefully easier for python users.

**Comment by davvid** [comment] 2022-03-25 00:29
Let me know if these were related or not. Closing for now.

**Closed by davvid** 2022-03-25 00:29 UTC
